// autogenerated
package com.github.egonw.odk.atomtypes;

import java.util.*;

import com.github.egonw.odk.interfaces.*;

public class AtomTypes {

  public Map<String,IAtomType> atomTypes =
    new HashMap<String,IAtomType>() {
      private static final long serialVersionUID = -1940564120967226668L;
      {
        put("Csp3", Csp3.getInstance());
        put("Csp2", Csp2.getInstance());
        put("Osp3", Osp3.getInstance());
        put("Osp2", Osp2.getInstance());
        put("Osp2co2", Osp2co2.getInstance());
        put("Nsp3", Nsp3.getInstance());
        put("Nsp2", Nsp2.getInstance());
        put("Nsp23", Nsp23.getInstance());
        put("Namide", Namide.getInstance());
        put("Noxide", Noxide.getInstance());
        put("Nthioamide", Nthioamide.getInstance());
        put("S2", S2.getInstance());
        put("S3", S3.getInstance());
        put("Sinyl2", Sinyl2.getInstance());
        put("Sonyl", Sonyl.getInstance());
        put("Sinyl", Sinyl.getInstance());
        put("Strioxide", Strioxide.getInstance());
        put("F", F.getInstance());
        put("Cl", Cl.getInstance());
        put("Clperchlorate", Clperchlorate.getInstance());
        put("Clchlorate", Clchlorate.getInstance());
        put("I", I.getInstance());
        put("I3", I3.getInstance());
        put("I5", I5.getInstance());
        put("Br", Br.getInstance());
        put("Pse3", Pse3.getInstance());
        put("Pate", Pate.getInstance());
        put("Pine", Pine.getInstance());
        put("Sisp3", Sisp3.getInstance());
        put("Snsp3", Snsp3.getInstance());
        put("As", As.getInstance());
        put("Tisp3", Tisp3.getInstance());
        put("B", B.getInstance());
        put("Se3", Se3.getInstance());
        put("Ge", Ge.getInstance());
      }
    };

}
