// autogenerated
package com.github.egonw.odk.atomtypes;

import java.util.ArrayList;
import java.util.List;

import com.github.egonw.odk.elements.Oxygen;
import com.github.egonw.odk.interfaces.IAtomType;
import com.github.egonw.odk.interfaces.IElement;
import com.github.egonw.odk.interfaces.IOrbitalType;
import com.github.egonw.odk.model.*;
import com.github.egonw.odk.model.orbitals.*;

public class Osp2co2 implements IAtomType {

	private static IAtomType type;

	private Osp2co2() {}

	public static IAtomType getInstance() {
		if (type == null) type = new Osp2co2();
		return type;
	}

	@Override
	public IElement getElement() {
		return Oxygen.getInstance();
	}

	@Override
	public String getName() {
		return "O.sp2.co2";
	}

	@Override
	public short getOxidationState() {
		return 6;
	}

	@Override
	public List<IOrbitalType> getOrbitalTypes() {
		List<IOrbitalType> orbitals = new ArrayList<IOrbitalType>();
		orbitals.add(LonePair.getInstance(Sp2.getInstance()));
		orbitals.add(LonePair.getInstance(Sp2.getInstance()));
		orbitals.add(SingleElectron.getInstance(Sp2.getInstance()));
		orbitals.add(SingleElectron.getInstance(Pz.getInstance()));
		return orbitals;
	}

}
