// autogenerated
package com.github.egonw.odk.atomtypes;

import java.util.ArrayList;
import java.util.List;

import com.github.egonw.odk.elements.Phosphorus;
import com.github.egonw.odk.interfaces.IAtomType;
import com.github.egonw.odk.interfaces.IElement;
import com.github.egonw.odk.interfaces.IOrbitalType;
import com.github.egonw.odk.model.*;
import com.github.egonw.odk.model.orbitals.*;

public class Pse3 implements IAtomType {

	private static IAtomType type;

	private Pse3() {}

	public static IAtomType getInstance() {
		if (type == null) type = new Pse3();
		return type;
	}

	@Override
	public IElement getElement() {
		return Phosphorus.getInstance();
	}

	@Override
	public String getName() {
		return "P.se.3";
	}

	@Override
	public short getOxidationState() {
		return 4;
	}

	@Override
	public List<IOrbitalType> getOrbitalTypes() {
		List<IOrbitalType> orbitals = new ArrayList<IOrbitalType>();
		orbitals.add(SingleElectron.getInstance(Sp3.getInstance()));
		orbitals.add(SingleElectron.getInstance(Sp3.getInstance()));
		orbitals.add(SingleElectron.getInstance(Sp3.getInstance()));
		orbitals.add(SingleElectron.getInstance(Sp3.getInstance()));
		return orbitals;
	}

}
