// autogenerated
package com.github.egonw.odk.atomtypes;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
  Csp3Test.class,
  Osp3Test.class,
  Nsp3Test.class,
  S3Test.class,
  SonylTest.class,
  FTest.class,
  ClperchlorateTest.class,
  Pse3Test.class,
  PateTest.class,
  PineTest.class,
  Sisp3Test.class,
  Snsp3Test.class,
  AsTest.class,
  Tisp3Test.class,
  BTest.class,
  Se3Test.class,
  GeTest.class})
public class AtomTypeTests {}
