// autogenerated
package com.github.egonw.odk.atomtypes;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
  Csp3Test.class,
  Csp2Test.class,
  Osp3Test.class,
  Osp2Test.class,
  Osp2co2Test.class,
  Nsp3Test.class,
  Nsp2Test.class,
  Nsp23Test.class,
  NamideTest.class,
  NthioamideTest.class,
  S2Test.class,
  S3Test.class,
  Sinyl2Test.class,
  SonylTest.class,
  SinylTest.class,
  StrioxideTest.class,
  FTest.class,
  ClperchlorateTest.class,
  ClchlorateTest.class,
  I3Test.class,
  I5Test.class,
  Pse3Test.class,
  PateTest.class,
  PineTest.class,
  Sisp3Test.class,
  Snsp3Test.class,
  AsTest.class,
  Tisp3Test.class,
  BTest.class,
  Se3Test.class,
  GeTest.class})
public class AtomTypeTests {}
