// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Actinium implements IElement {

	private final static String SYMBOL = "Ac";
	private static IElement instance;

	private Actinium() {};

	public static IElement getInstance() {
		if (Actinium.instance == null)
			Actinium.instance = new Actinium();
		return Actinium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 89;
	}

}
