// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Aluminum implements IElement {

	private final static String SYMBOL = "Al";
	private static IElement instance;

	private Aluminum() {};

	public static IElement getInstance() {
			Aluminum.instance = new Aluminum();
		return Aluminum.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 13;
	}

}
