// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Americium implements IElement {

	private final static String SYMBOL = "Am";
	private static IElement instance;

	private Americium() {};

	public static IElement getInstance() {
			Americium.instance = new Americium();
		return Americium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 95;
	}

}
