// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Argon implements IElement {

	private final static String SYMBOL = "Ar";
	private static IElement instance;

	private Argon() {};

	public static IElement getInstance() {
			Argon.instance = new Argon();
		return Argon.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 18;
	}

}
