// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Astatine implements IElement {

	private final static String SYMBOL = "At";
	private static IElement instance;

	private Astatine() {};

	public static IElement getInstance() {
			Astatine.instance = new Astatine();
		return Astatine.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 85;
	}

}
