// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Barium implements IElement {

	private final static String SYMBOL = "Ba";
	private static IElement instance;

	private Barium() {};

	public static IElement getInstance() {
		if (Barium.instance == null)
			Barium.instance = new Barium();
		return Barium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 56;
	}

}
