// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Berkelium implements IElement {

	private final static String SYMBOL = "Bk";
	private static IElement instance;

	private Berkelium() {};

	public static IElement getInstance() {
			Berkelium.instance = new Berkelium();
		return Berkelium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 97;
	}

}
