// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Beryllium implements IElement {

	private final static String SYMBOL = "Be";
	private static IElement instance;

	private Beryllium() {};

	public static IElement getInstance() {
		if (Beryllium.instance == null)
			Beryllium.instance = new Beryllium();
		return Beryllium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 4;
	}

}
