// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Bismuth implements IElement {

	private final static String SYMBOL = "Bi";
	private static IElement instance;

	private Bismuth() {};

	public static IElement getInstance() {
		if (Bismuth.instance == null)
			Bismuth.instance = new Bismuth();
		return Bismuth.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 83;
	}

}
