// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Bohrium implements IElement {

	private final static String SYMBOL = "Bh";
	private static IElement instance;

	private Bohrium() {};

	public static IElement getInstance() {
		if (Bohrium.instance == null)
			Bohrium.instance = new Bohrium();
		return Bohrium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 107;
	}

}
