// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Bromine implements IElement {

	private final static String SYMBOL = "Br";
	private static IElement instance;

	private Bromine() {};

	public static IElement getInstance() {
			Bromine.instance = new Bromine();
		return Bromine.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 35;
	}

}
