// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Cadmium implements IElement {

	private final static String SYMBOL = "Cd";
	private static IElement instance;

	private Cadmium() {};

	public static IElement getInstance() {
		if (Cadmium.instance == null)
			Cadmium.instance = new Cadmium();
		return Cadmium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 48;
	}

}
