// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Californium implements IElement {

	private final static String SYMBOL = "Cf";
	private static IElement instance;

	private Californium() {};

	public static IElement getInstance() {
			Californium.instance = new Californium();
		return Californium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 98;
	}

}
