// autogenerated

package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Carbon implements IElement {

	private final static String SYMBOL = "C"; 
	private static IElement instance;

	private Carbon() {};

	public static IElement getInstance() {
		if (Carbon.instance == null)
			Carbon.instance = new Carbon();
		return Carbon.instance;
	}
	
	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 6;
	}

}
