// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Cerium implements IElement {

	private final static String SYMBOL = "Ce";
	private static IElement instance;

	private Cerium() {};

	public static IElement getInstance() {
		if (Cerium.instance == null)
			Cerium.instance = new Cerium();
		return Cerium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 58;
	}

}
