// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Chlorine implements IElement {

	private final static String SYMBOL = "Cl";
	private static IElement instance;

	private Chlorine() {};

	public static IElement getInstance() {
			Chlorine.instance = new Chlorine();
		return Chlorine.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 17;
	}

}
