// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Copper implements IElement {

	private final static String SYMBOL = "Cu";
	private static IElement instance;

	private Copper() {};

	public static IElement getInstance() {
			Copper.instance = new Copper();
		return Copper.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 29;
	}

}
