// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Curium implements IElement {

	private final static String SYMBOL = "Cm";
	private static IElement instance;

	private Curium() {};

	public static IElement getInstance() {
		if (Curium.instance == null)
			Curium.instance = new Curium();
		return Curium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 96;
	}

}
