// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Dubnium implements IElement {

	private final static String SYMBOL = "Db";
	private static IElement instance;

	private Dubnium() {};

	public static IElement getInstance() {
		if (Dubnium.instance == null)
			Dubnium.instance = new Dubnium();
		return Dubnium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 105;
	}

}
