// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Dysprosium implements IElement {

	private final static String SYMBOL = "Dy";
	private static IElement instance;

	private Dysprosium() {};

	public static IElement getInstance() {
			Dysprosium.instance = new Dysprosium();
		return Dysprosium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 66;
	}

}
