// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Erbium implements IElement {

	private final static String SYMBOL = "Er";
	private static IElement instance;

	private Erbium() {};

	public static IElement getInstance() {
			Erbium.instance = new Erbium();
		return Erbium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 68;
	}

}
