// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Fermium implements IElement {

	private final static String SYMBOL = "Fm";
	private static IElement instance;

	private Fermium() {};

	public static IElement getInstance() {
			Fermium.instance = new Fermium();
		return Fermium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 100;
	}

}
