// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Fluorine implements IElement {

	private final static String SYMBOL = "F";
	private static IElement instance;

	private Fluorine() {};

	public static IElement getInstance() {
			Fluorine.instance = new Fluorine();
		return Fluorine.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 9;
	}

}
