// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Francium implements IElement {

	private final static String SYMBOL = "Fr";
	private static IElement instance;

	private Francium() {};

	public static IElement getInstance() {
			Francium.instance = new Francium();
		return Francium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 87;
	}

}
