// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Gadolinium implements IElement {

	private final static String SYMBOL = "Gd";
	private static IElement instance;

	private Gadolinium() {};

	public static IElement getInstance() {
			Gadolinium.instance = new Gadolinium();
		return Gadolinium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 64;
	}

}
