// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Germanium implements IElement {

	private final static String SYMBOL = "Ge";
	private static IElement instance;

	private Germanium() {};

	public static IElement getInstance() {
		if (Germanium.instance == null)
			Germanium.instance = new Germanium();
		return Germanium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 32;
	}

}
