// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Hafnium implements IElement {

	private final static String SYMBOL = "Hf";
	private static IElement instance;

	private Hafnium() {};

	public static IElement getInstance() {
			Hafnium.instance = new Hafnium();
		return Hafnium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 72;
	}

}
