// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Hassium implements IElement {

	private final static String SYMBOL = "Hs";
	private static IElement instance;

	private Hassium() {};

	public static IElement getInstance() {
			Hassium.instance = new Hassium();
		return Hassium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 108;
	}

}
