// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Helium implements IElement {

	private final static String SYMBOL = "He";
	private static IElement instance;

	private Helium() {};

	public static IElement getInstance() {
		if (Helium.instance == null)
			Helium.instance = new Helium();
		return Helium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 2;
	}

}
