// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Holmium implements IElement {

	private final static String SYMBOL = "Ho";
	private static IElement instance;

	private Holmium() {};

	public static IElement getInstance() {
			Holmium.instance = new Holmium();
		return Holmium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 67;
	}

}
