// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Hydrogen implements IElement {

	private final static String SYMBOL = "H";
	private static IElement instance;

	private Hydrogen() {};

	public static IElement getInstance() {
			Hydrogen.instance = new Hydrogen();
		return Hydrogen.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 1;
	}

}
