// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Iodine implements IElement {

	private final static String SYMBOL = "I";
	private static IElement instance;

	private Iodine() {};

	public static IElement getInstance() {
			Iodine.instance = new Iodine();
		return Iodine.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 53;
	}

}
