// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Iridium implements IElement {

	private final static String SYMBOL = "Ir";
	private static IElement instance;

	private Iridium() {};

	public static IElement getInstance() {
		if (Iridium.instance == null)
			Iridium.instance = new Iridium();
		return Iridium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 77;
	}

}
