// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Iron implements IElement {

	private final static String SYMBOL = "Fe";
	private static IElement instance;

	private Iron() {};

	public static IElement getInstance() {
			Iron.instance = new Iron();
		return Iron.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 26;
	}

}
