// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Lanthanum implements IElement {

	private final static String SYMBOL = "La";
	private static IElement instance;

	private Lanthanum() {};

	public static IElement getInstance() {
			Lanthanum.instance = new Lanthanum();
		return Lanthanum.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 57;
	}

}
