// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Lawrencium implements IElement {

	private final static String SYMBOL = "Lr";
	private static IElement instance;

	private Lawrencium() {};

	public static IElement getInstance() {
		if (Lawrencium.instance == null)
			Lawrencium.instance = new Lawrencium();
		return Lawrencium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 103;
	}

}
