// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Lutetium implements IElement {

	private final static String SYMBOL = "Lu";
	private static IElement instance;

	private Lutetium() {};

	public static IElement getInstance() {
			Lutetium.instance = new Lutetium();
		return Lutetium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 71;
	}

}
