// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Magnesium implements IElement {

	private final static String SYMBOL = "Mg";
	private static IElement instance;

	private Magnesium() {};

	public static IElement getInstance() {
			Magnesium.instance = new Magnesium();
		return Magnesium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 12;
	}

}
