// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Mercury implements IElement {

	private final static String SYMBOL = "Hg";
	private static IElement instance;

	private Mercury() {};

	public static IElement getInstance() {
		if (Mercury.instance == null)
			Mercury.instance = new Mercury();
		return Mercury.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 80;
	}

}
