// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Neodymium implements IElement {

	private final static String SYMBOL = "Nd";
	private static IElement instance;

	private Neodymium() {};

	public static IElement getInstance() {
		if (Neodymium.instance == null)
			Neodymium.instance = new Neodymium();
		return Neodymium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 60;
	}

}
