// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Neon implements IElement {

	private final static String SYMBOL = "Ne";
	private static IElement instance;

	private Neon() {};

	public static IElement getInstance() {
			Neon.instance = new Neon();
		return Neon.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 10;
	}

}
