// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Neptunium implements IElement {

	private final static String SYMBOL = "Np";
	private static IElement instance;

	private Neptunium() {};

	public static IElement getInstance() {
			Neptunium.instance = new Neptunium();
		return Neptunium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 93;
	}

}
