// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Nickel implements IElement {

	private final static String SYMBOL = "Ni";
	private static IElement instance;

	private Nickel() {};

	public static IElement getInstance() {
			Nickel.instance = new Nickel();
		return Nickel.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 28;
	}

}
