// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Niobium implements IElement {

	private final static String SYMBOL = "Nb";
	private static IElement instance;

	private Niobium() {};

	public static IElement getInstance() {
		if (Niobium.instance == null)
			Niobium.instance = new Niobium();
		return Niobium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 41;
	}

}
