// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Nobelium implements IElement {

	private final static String SYMBOL = "No";
	private static IElement instance;

	private Nobelium() {};

	public static IElement getInstance() {
		if (Nobelium.instance == null)
			Nobelium.instance = new Nobelium();
		return Nobelium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 102;
	}

}
