// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Phosphorus implements IElement {

	private final static String SYMBOL = "P";
	private static IElement instance;

	private Phosphorus() {};

	public static IElement getInstance() {
		if (Phosphorus.instance == null)
			Phosphorus.instance = new Phosphorus();
		return Phosphorus.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 15;
	}

}
