// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Platinum implements IElement {

	private final static String SYMBOL = "Pt";
	private static IElement instance;

	private Platinum() {};

	public static IElement getInstance() {
		if (Platinum.instance == null)
			Platinum.instance = new Platinum();
		return Platinum.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 78;
	}

}
