// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Polonium implements IElement {

	private final static String SYMBOL = "Po";
	private static IElement instance;

	private Polonium() {};

	public static IElement getInstance() {
		if (Polonium.instance == null)
			Polonium.instance = new Polonium();
		return Polonium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 84;
	}

}
