// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Promethium implements IElement {

	private final static String SYMBOL = "Pm";
	private static IElement instance;

	private Promethium() {};

	public static IElement getInstance() {
		if (Promethium.instance == null)
			Promethium.instance = new Promethium();
		return Promethium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 61;
	}

}
