// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Protactinium implements IElement {

	private final static String SYMBOL = "Pa";
	private static IElement instance;

	private Protactinium() {};

	public static IElement getInstance() {
			Protactinium.instance = new Protactinium();
		return Protactinium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 91;
	}

}
