// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Radium implements IElement {

	private final static String SYMBOL = "Ra";
	private static IElement instance;

	private Radium() {};

	public static IElement getInstance() {
			Radium.instance = new Radium();
		return Radium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 88;
	}

}
