// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Radon implements IElement {

	private final static String SYMBOL = "Rn";
	private static IElement instance;

	private Radon() {};

	public static IElement getInstance() {
		if (Radon.instance == null)
			Radon.instance = new Radon();
		return Radon.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 86;
	}

}
