// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Rhenium implements IElement {

	private final static String SYMBOL = "Re";
	private static IElement instance;

	private Rhenium() {};

	public static IElement getInstance() {
		if (Rhenium.instance == null)
			Rhenium.instance = new Rhenium();
		return Rhenium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 75;
	}

}
