// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Rubidium implements IElement {

	private final static String SYMBOL = "Rb";
	private static IElement instance;

	private Rubidium() {};

	public static IElement getInstance() {
			Rubidium.instance = new Rubidium();
		return Rubidium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 37;
	}

}
