// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Ruthenium implements IElement {

	private final static String SYMBOL = "Ru";
	private static IElement instance;

	private Ruthenium() {};

	public static IElement getInstance() {
			Ruthenium.instance = new Ruthenium();
		return Ruthenium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 44;
	}

}
