// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Rutherfordium implements IElement {

	private final static String SYMBOL = "Rf";
	private static IElement instance;

	private Rutherfordium() {};

	public static IElement getInstance() {
			Rutherfordium.instance = new Rutherfordium();
		return Rutherfordium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 104;
	}

}
