// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Scandium implements IElement {

	private final static String SYMBOL = "Sc";
	private static IElement instance;

	private Scandium() {};

	public static IElement getInstance() {
		if (Scandium.instance == null)
			Scandium.instance = new Scandium();
		return Scandium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 21;
	}

}
