// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Seaborgium implements IElement {

	private final static String SYMBOL = "Sg";
	private static IElement instance;

	private Seaborgium() {};

	public static IElement getInstance() {
		if (Seaborgium.instance == null)
			Seaborgium.instance = new Seaborgium();
		return Seaborgium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 106;
	}

}
