// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Selenium implements IElement {

	private final static String SYMBOL = "Se";
	private static IElement instance;

	private Selenium() {};

	public static IElement getInstance() {
			Selenium.instance = new Selenium();
		return Selenium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 34;
	}

}
