// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Sulfur implements IElement {

	private final static String SYMBOL = "S";
	private static IElement instance;

	private Sulfur() {};

	public static IElement getInstance() {
		if (Sulfur.instance == null)
			Sulfur.instance = new Sulfur();
		return Sulfur.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 16;
	}

}
