// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Tantalum implements IElement {

	private final static String SYMBOL = "Ta";
	private static IElement instance;

	private Tantalum() {};

	public static IElement getInstance() {
			Tantalum.instance = new Tantalum();
		return Tantalum.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 73;
	}

}
