// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Terbium implements IElement {

	private final static String SYMBOL = "Tb";
	private static IElement instance;

	private Terbium() {};

	public static IElement getInstance() {
			Terbium.instance = new Terbium();
		return Terbium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 65;
	}

}
