// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Thulium implements IElement {

	private final static String SYMBOL = "Tm";
	private static IElement instance;

	private Thulium() {};

	public static IElement getInstance() {
			Thulium.instance = new Thulium();
		return Thulium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 69;
	}

}
