// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Tin implements IElement {

	private final static String SYMBOL = "Sn";
	private static IElement instance;

	private Tin() {};

	public static IElement getInstance() {
			Tin.instance = new Tin();
		return Tin.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 50;
	}

}
