// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Titanium implements IElement {

	private final static String SYMBOL = "Ti";
	private static IElement instance;

	private Titanium() {};

	public static IElement getInstance() {
		if (Titanium.instance == null)
			Titanium.instance = new Titanium();
		return Titanium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 22;
	}

}
