// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Tungsten implements IElement {

	private final static String SYMBOL = "W";
	private static IElement instance;

	private Tungsten() {};

	public static IElement getInstance() {
			Tungsten.instance = new Tungsten();
		return Tungsten.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 74;
	}

}
