// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Ununbium implements IElement {

	private final static String SYMBOL = "Uub";
	private static IElement instance;

	private Ununbium() {};

	public static IElement getInstance() {
			Ununbium.instance = new Ununbium();
		return Ununbium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 112;
	}

}
