// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Xenon implements IElement {

	private final static String SYMBOL = "Xe";
	private static IElement instance;

	private Xenon() {};

	public static IElement getInstance() {
			Xenon.instance = new Xenon();
		return Xenon.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 54;
	}

}
