// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Ytterbium implements IElement {

	private final static String SYMBOL = "Yb";
	private static IElement instance;

	private Ytterbium() {};

	public static IElement getInstance() {
		if (Ytterbium.instance == null)
			Ytterbium.instance = new Ytterbium();
		return Ytterbium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 70;
	}

}
