// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Yttrium implements IElement {

	private final static String SYMBOL = "Y";
	private static IElement instance;

	private Yttrium() {};

	public static IElement getInstance() {
		if (Yttrium.instance == null)
			Yttrium.instance = new Yttrium();
		return Yttrium.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 39;
	}

}
