// autogenerated
package com.github.egonw.odk.elements;

import com.github.egonw.odk.interfaces.IElement;

public final class Zinc implements IElement {

	private final static String SYMBOL = "Zn";
	private static IElement instance;

	private Zinc() {};

	public static IElement getInstance() {
		if (Zinc.instance == null)
			Zinc.instance = new Zinc();
		return Zinc.instance;
	}

	@Override
	public String getSymbol() {
		return SYMBOL;
	}

	@Override
	public short getAtomicNumber() {
		return 30;
	}

}
